language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --prefer-source --no-interaction

script:
  - php ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php ./vendor/bin/coveralls
